apiVersion: v1
data:
  INFLUXDB_ADMIN_USER: cm9vdA==
  INFLUXDB_ADMIN_USER_PASSWORD: cGFzc3dvcmQ=
  INFLUXDB_DB: bW9uaXRvcmluZw==
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_HTTP_AUTH_ENABLED: dHJ1ZQ==
  INFLUXDB_READ_USER: cmVhZG9ubHk=
  INFLUXDB_USER: dXNlcg==
  INFLUXDB_USER_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: influxdb-creds